### ISSUE TITLE
How do you play the mod?

### ISSUE THREAD

**Issue by gabriel-dehan** [GraysonnG/InfiniteSpire#10]
Hello!

Sorry if this is a stupid question, but I have everything installed properly but I can't seem to find a way to play the game in Infinite Spire, is it a custom game mode ? They are still unlocked as I haven't won a daily climb yet. 

Really interested in this whole perks stuff, but I can't seem to find my way in :D 

Thanks

**Comment by GraysonnG** [comment]
For the time being the only way to get perks is to play with the endless mod from custom mode. But i am aiming to make it so you can unlock endless in a normal run.

**Comment by gabriel-dehan** [comment]
Okay thanks, is there a way to unlock the custom mode using the command tools?

**Comment by GraysonnG** [comment]
Unfortunately not right now.

**Comment by GraysonnG** [comment]
Ahh Strike that

```
if you just want to unlock custom, go to your local slay the spire folder, then the preferences/betapreferences subfolder (depending on if you play in the beta branch) then open the STSAchivements File.

Add

"LUCKY_DAY": "true",

somewhere in there to unlock custom```

**Comment by gabriel-dehan** [comment]
Thanks a lot!

**Comment by GraysonnG** [comment]
The perks room shows up at in the exordium after you have defeated the 3rd floor boss. This mechanic is being changed in the next update though.
