### ISSUE TITLE
Retaliate referencing unused keyword.

### ISSUE THREAD

**Issue by spikeof2010** [GraysonnG/InfiniteSpire#11]
(This might be due to me using this with the construct mod)
For whatever reason, there's an addtional rules reminders text detailing what the "Broken" keyword is, even if it's unrelated to the skill itself.

**Comment by GraysonnG** [comment]
Can you provide a list of mods, what versions they are, and a screenshot of the issue?

**Comment by GraysonnG** [comment]
The dev of Construct let me know that Broken is being removed anyways so it should be fixed the next time it is updated.
