### ISSUE TITLE
unable to play infinitely. 

### ISSUE THREAD

**Issue by ItsonlyTelch** [GraysonnG/InfiniteSpire#12]
So, i have no clue how to start playing infinitely, Ive ran the mod by its self and with other mods (replay the spire) and made it to the last boss of the base game. any clue how i could uhm start to play infinitely?

**Comment by GraysonnG** [comment]
You will have to enable it through custom mode for now, however I am adding a feature in the next update to allow you to start climbing infinitely soon.
