### ISSUE TITLE
Nightmare crashes when 50 damage taken occurs

### ISSUE THREAD

**Issue by dackid19** [GraysonnG/InfiniteSpire#20]
Unfortunately, the nightmare elite crashes when his effect triggers. Super neat Idea and I am excited to know when it is fixed. :)

**Comment by GraysonnG** [comment]
If possible could you provide a crashlog, as I am unable to duplicate the crash on my end.

**Comment by dackid19** [comment]
Sorry, I'm not that knowledgable when it comes to the innerworkings of this game. Where can I find this crashlog.
