### ISSUE TITLE
Infinite Crash. 

### ISSUE THREAD

**Issue by dackid19** [GraysonnG/InfiniteSpire#33]
Unfortunately, Infinite Spire has crashed on me after I opened up the quest screen. I will send you a crash log. Thanks in advance :)
[SlayTheSpire.log](https://github.com/GraysonnG/InfiniteSpire/files/2338643/SlayTheSpire.log)

**Comment by GraysonnG** [comment]
Hmm looks like someone is manipulating the card lib in a way I wasn't expecting
