### ISSUE TITLE
Games Crash

### ISSUE THREAD

**Issue by VampyreRain** [GraysonnG/InfiniteSpire#43]
Every game I've had has reached a point where it cannot seem to load a fight, after getting the pride cards. There will be a point where the game just closes when loading a fight.

**Comment by GraysonnG** [comment]
Can you list the mods you were using.

**Comment by VampyreRain** [comment]
where would I find the crashlog? I was originally only using basemod and infinitespire, but recently ive added always whale

**Comment by VampyreRain** [comment]
[SlayTheSpire_201810062008_1.log.zip](https://github.com/GraysonnG/InfiniteSpire/files/2453369/SlayTheSpire_201810062008_1.log.zip)

**Comment by GraysonnG** [comment]
Ahh that was the focusing shard bug. It has been fixed in the latest patches. 👍
