### ISSUE TITLE
Many Infinite spire relics cannot be added through BaseMod Console 

### ISSUE THREAD

**Issue by huoyanak47** [GraysonnG/InfiniteSpire#63]
As the title says, infinite spire relics, and some cards also, cannot be spawned in through the `relic add ___` or `card add ___` function. Tried spawning dark rift and neurotoxin, and neither worked. However, cards from other mods (replay the spire, and custom classes all work correctly)

**Comment by GraysonnG** [comment]
You have to prefix the relic name with `infinitespire:`
