### ISSUE TITLE
Infinite No Longer Working After Lord Of Annihilation

### ISSUE THREAD

**Issue by Frumgor** [GraysonnG/InfiniteSpire#73]
I'm not sure if this is a failure on my part that is gameplay related or a mod conflict of some sort.  On my last couple playthroughs I have had an issue with truly infinite climbing being impossible.  After the third time through the spire with the endless quest activated, I encounter the Lord of Annihilation, as expected.  However, after defeating him, the game proceeds to Act 4, whether or not I have collected the three keys.  After defeating the heart, I receive more quests for my quest log, but the game proceeds to the ending splash screen and my save file is removed.  The mods I was running for these runs were as follows: BaseMod, StSLib, FetchMod, RelicSorter, Infinite Spire, Conspire, Replay the Spire, The Construct.  Any idea what could be going on here?

**Comment by GraysonnG** [comment]
Ahh I must have broken something, while making some changes to Lord of Annihilation. Unfortunately I can't do much to fix it at the moment expect a fix sometime soon!
