### ISSUE TITLE
How to active infinite?

### ISSUE THREAD

**Issue by manhquyet-nguyen** [GraysonnG/InfiniteSpire#74]
I searched through the issues and readme but didn't find any clue how to play this mode infinitely.
The guide said that I will be able to choose infinite or not after killing some nightmares, but even after kill the second nightmare I still don't figure out how to active it.
Is there a button / config somewhere?

**Comment by GraysonnG** [comment]
The option should be in the config, although i don't understand why it is defaulting to false.
